--- 
title: "Statistics"
author: "Benjamin Buchwitz"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: bchwtz/bchwtz-stat
description: "Statistics Course Notes"
---

# Einführung {-}

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown', 'kableExtra'
), 'packages.bib')
```

```{r, include=FALSE}
# Load Packages
library("fhswf")
library("tidyverse")
library("knitr")
library("kableExtra")
knitr::opts_chunk$set(echo = TRUE, fig.align = "center")
```

Herzlich Willkommen zum Kurs Statistik

| Woche| Thema             | Vorlesung    |
| ---: | :--------         | :---:        |
| 1    | Grundlagen        | [PDF](slides/01-Grundlagen.pdf)    |
|      | Häufigkeit        | [PDF](slides/02-Haeufigkeit.pdf)   |
| 2    | Maßzahlen         | [PDF](slides/03-Masszahlen.pdf)     |
| 3    | Zusammenhang      | [PDF](slides/04-Zusammenhang.pdf)     |
| 4    | Kombinatorik      | [PDF](slides/05-Kombinatorik.pdf)     |
| 5    | Wahrscheinlichkeitsrechnung      | [PDF](slides/06-Wahrscheinlichkeitsrechnung.pdf)     |
