# (PART\*) Appendix {-} 

# Datacamp {-}

Die Anmeldung bei [DataCamp](https://www.datacamp.com/groups/shared_links/6c29db40d79200c5c48aca9ec64682de22a5e604bf61b174ef9535f3173f9518) muss mit einer `@fh-swf.de`-Emailadresse erfolgen. 

[DataCamp Zugang](https://www.datacamp.com/groups/shared_links/6c29db40d79200c5c48aca9ec64682de22a5e604bf61b174ef9535f3173f9518)

# Gruppenarbeit {-}

Die Bewertung der Gruppenarbeiten erfolgt mit dem folgenden Formular:

- [Download Beispielbogen](data/2022 - Statistik - Gruppensprecher - Gruppenname.pdf)
- [Download Bewertungsformular](data/2022- Statistik - Gruppenarbeiten.xlsm)


# Evaluation {-}

```{r, eval=F}
stats_ss2021 <- tribble(
  ~date, ~vg, ~g, ~n, ~b, ~vb, ~total,
  "07.04.2021",45,71,7,0,0,128,
  "12.04.2021",24,63,10,0,0,119,
  "14.04.2021",34,55,20,0,0,118,
  "19.04.2021",15,54,12,2,0,97,
  "26.04.2021",17,42,8,2,1,99,
  "28.04.2021",55,38,13,1,0,115,
  "05.05.2021",23,37,13,1,0,110
)
evcnames<- c("Datum","sehr zufrieden", "zufrieden", 
           "weder zufrieden noch unzufrieden", 
           "unzufrieden", "sehr unzufrieden", "anwesend")
kable(stats_ss2021, booktabbs=T, col.names = evcnames)
```



# System Info {-}
```{r}
Sys.time()
sessionInfo()
```

